src/ruli_addr.c: Add missing format string
fixes

| ruli_addr.c: In function 'ruli_in_snprint':
| ruli_addr.c:491:5: error: format not a string literal and no format arguments [-Werror=format-security]
|      return snprintf(buf, size, inet_ntoa(addr->ipv4));
|      ^~~~~~

Signed-off-by: Khem Raj <raj.khem@gmail.com>